### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by captainnima** [lorint/AdventureWorks-for-Postgres#12]
I am on a Mac. I have everything installed. From Terminal, when I run the psql commands, it asks for my password which I type in but it fails. The problem seems to be the it defaults to my username instead of the Postgres account which is in the database. Any suggestions how I can do this?

**Comment by loganphillips792** [comment]
Can you provide the command you are running?

**Comment by captainnima** [comment]
I run the psql -d command on my Mac. I am logged in as my super user account and when I run the command, it asks for my password. I enter it but it says “Sorry”. I connected to Postgres from the command line but when I do, I am not sure how to run the install.sql. I tried switching to root and running the command but it still asks for the root password and then it fails. I put in the Postgres password also but it fails.

**Comment by captainnima** [comment]
I figured it out. The command needs to be “psql postgres -d adventureworks < install.sql” to include the username for the database. Would you mind modifying your ReadMe to indicate that?

**Comment by lorint** [comment]
@captainnima -- have now added in the README the suggestion to try the **-U** switch:
e7dad283a21a4c3c410670de45a90ffd60efe10b

Hope that this is helpful -- let me know if you think it should be further revised.
