### ISSUE TITLE
MIT License?

### ISSUE THREAD

**Issue by paulirwin** [lorint/AdventureWorks-for-Postgres#14]
Hello, thank you for this sample database. I am hoping to use it for unit test cases in an open source project. Would you mind adding an MIT license to this repository so there are no licensing concerns? 

Note that the Microsoft official sample source for the AdventureWorks database is MIT licensed so there should not be any concerns with incompatible licenses: https://github.com/microsoft/sql-server-samples/blob/master/license.txt

Thanks!

**Comment by lorint** [comment]
> ... adding an MIT license to this repository

Have now added a LICENSE file with an MIT license in this commit:
b37c060c3c3064b501cb479fe1085ed9141c2f66

Let me know if you think anything else is necessary.

**Comment by paulirwin** [comment]
Perfect, thank you!
