### ISSUE TITLE
Unable to run install.sql

### ISSUE THREAD

**Issue by arockiya** [lorint/AdventureWorks-for-Postgres#2]
I am unable to run install.sql through Query editor in PGAdmin III. its giving multiple error. Or can you pls suggest how else we can run this file. 

PS: I am trying this in Windows 7 desktop.

**Comment by lorint** [comment]
Hmmmm ... I realize that the last push didn't include one critical line in update_csvs.rb that properly sets up quotes in blocks of XML.  This commit should hopefully set things in order:

41898420120ccd7afae4d261035dda6fb9fb4e0a

At least it's flying on the Windows 8 machine I have here to test with.

You'll need to start from scratch -- remove your existing CSVs and unzip fresh CSVs to work with, and follow all the steps.

Thanks for bringing this to my attention, and please let me know if things work out.

**Comment by arockiya** [comment]
Sorry for the late update. Issue resolved. Thank you so much.
